postgresql:
  image: postgres:11
  ports:
    - 5432:5432
  environment:
    - PGDATA=/postgresql
    - PG_USER=postgres
    - PG_PASSWORD=myPassword
  volumes:
    - ./tmp/data/postgresql:/postgresql